import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import InnerMainLayout from './components/inner-layout'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className={nunito.className}>
          {/* <div className='flex flex-col md:flex-row'>
            <div>
              <Navbar />
            </div>
            <div>
              {children}
            </div>
          </div> */}
          <InnerMainLayout children={children} />
      </body>
    </html>
  )
}
